# Generated by Django 5.2.4 on 2025-07-26 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cihaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri_no', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('tur', models.CharField(max_length=100)),
                ('kurulum_tarihi', models.DateField()),
                ('bakım_aralığı_gun', models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='Bakim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('aciklama', models.TextField(blank=True)),
                ('cihaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakimlar', to='sistem.cihaz')),
            ],
        ),
    ]
