# Generated by Django 5.2.4 on 2025-07-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('muhendis', 'Mühendis'), ('tekniker', 'Tekniker')], max_length=10),
        ),
    ]
