# Generated by Django 5.2.4 on 2025-07-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0003_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bakim',
            name='geri_bildirim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bakim',
            name='tamamlandi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bakim',
            name='tekniker',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'tekniker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
