# Generated by Django 5.2.4 on 2025-07-26 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0004_bakim_geri_bildirim_bakim_tamamlandi_bakim_tekniker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakim',
            name='geri_bildirim',
        ),
        migrations.RemoveField(
            model_name='bakim',
            name='tamamlandi',
        ),
        migrations.RemoveField(
            model_name='bakim',
            name='tekniker',
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='model',
            field=models.CharField(choices=[('hp_laserjet', 'HP LaserJet'), ('epson_scanner', 'Epson Scanner'), ('dell_optiplex', 'Dell OptiPlex'), ('lenovo_thinkpad', 'Lenovo ThinkPad'), ('diger', 'Diğer')], default='diger', max_length=100),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='tur',
            field=models.CharField(choices=[('yazici', 'Yazıcı'), ('tarayici', 'Tarayıcı'), ('bilgisayar', 'Bilgisayar'), ('sunucu', 'Sunucu'), ('diger', 'Diğer')], default='diger', max_length=100),
        ),
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField()),
                ('atama_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('geri_bildirim', models.TextField(blank=True)),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='bekliyor', max_length=20)),
                ('cihaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to='sistem.cihaz')),
                ('muhendis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atanan_gorevler', to=settings.AUTH_USER_MODEL)),
                ('tekniker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yapilan_gorevler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
