# Generated by Django 5.2.4 on 2025-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0005_remove_bakim_geri_bildirim_remove_bakim_tamamlandi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihaz',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='tur',
            field=models.CharField(max_length=100),
        ),
    ]
