# Generated by Django 5.2.4 on 2025-07-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0006_alter_cihaz_model_alter_cihaz_tur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihaz',
            name='model',
            field=models.CharField(default='diger', max_length=100),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='tur',
            field=models.CharField(default='diger', max_length=100),
        ),
    ]
