# Generated by Django 5.2.4 on 2025-07-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0008_alter_cihaz_model_alter_cihaz_tur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorev',
            name='cihaz',
        ),
        migrations.AddField(
            model_name='gorev',
            name='bakim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to='sistem.bakim'),
            preserve_default=False,
        ),
    ]
