# Generated by Django 5.2.4 on 2025-07-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0010_profile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_approved',
        ),
    ]
